name: GitHub Pages Deploy
on:
  push:
    branches: [deploy]
jobs:
  deployment:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Install npm dependencies
        run: npm ci

      - name: Build Next.js project
        run: npm run build

      - name: Deploy to external repository
        env:
          API_GITHUB_TOKEN: ${{ secrets.API_GITHUB_TOKEN }}
          username: wendellavila
          email: wendelljcavila@gmail.com
          build_dir: out
          source_repo: portfolio_next
          deploy_repo: wendellavila.github.io
          deploy_branch: main
        run: |
          git config user.name "$username"
          git config user.email "$email"

          git clone "https://user:$API_GITHUB_TOKEN@github.com/$username/$deploy_repo" deploy_repo
          cd deploy_repo
          git checkout "$deploy_branch"
          cd ..

          mkdir tmp
          cp deploy_repo/README.md tmp
          cp deploy_repo/.nojekyll tmp

          rm -rf deploy_repo/*

          cp -r ${{ env.build_dir }}/* deploy_repo
          cp -r tmp/* deploy_repo

          cd deploy_repo
          git add .
          git commit -m "ci: Auto deploy with GitHub Actions. Source: $username/$source_repo"
          git push origin main
